# Set another prefix
set-option -g prefix  C-b
set-option -g prefix2 C-a

# ZSH addition
unbind-key C-a
  bind-key C-a send-prefix

# Enable mouse mode
setw -g mouse on

# Use Alt+Arrowkeys to switch panes
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# Shift arrows to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Set easier windowpane split keys
bind-key Left  split-window -h -c "#{pane_current_path}"
bind-key Right split-window -h -c "#{pane_current_path}" 
bind-key Up    split-window -v -c "#{pane_current_path}" 
bind-key Down  split-window -v -c "#{pane_current_path}" 

# Open new window
bind c new-window -c "#{pane_current_path}"

# Bottom bar & customizations
set -g status-style bg=blue
set -g status-right "[%Y-%m-%d] [%H:%M:%S]"
set -g status-interval 1
set -g default-terminal "xterm-256color"

# Add key for config reload within tmux
bind-key r source-file $HOME/.tmux.conf \; display-message " --> tmux.conf reloaded."
